---
title: "Effects of fluid intake on 30-day mortality in sepsis patients"
author: "Ian Waudby-Smith"
date: "6/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(purrr)

load('sepsis_cs.RData')


plot_df <- data.frame(t = rep(times, 2), 
                      bound = c(cs_ate$l, cs_ate$u),
                      upper_lower = c(rep('l', length(cs_ate$l)),
                                      rep('u', length(cs_ate$u))))

plt_cs <- 
  ggplot() + 
  geom_line(aes(x=t, y=bound), 
            data=plot_df[plot_df$upper_lower=='l',]) +
  geom_line(aes(x=t, y=bound), 
            data=plot_df[plot_df$upper_lower=='u',]) +
  ylab('Confidence sequences for the\naverage treatment effect') + xlab('Time') +
  scale_x_log10(breaks = scales::trans_breaks("log10",
                                              function(x) 10^x),
                labels = scales::trans_format("log10",
                                              scales::math_format(10^.x))) +
  annotation_logticks(colour = "grey", side = "b") + 
  theme_fn() + 
  theme(text = element_text(family="serif")) +
  scale_color_brewer(palette=palette)

ggsave('figures/sepsis.pdf',
       width=plt_width, height=plt_height, units='cm')
plt_cs
```

