---
title: "Effects of fluid intake on 30-day mortality in sepsis patients"
author: "Ian Waudby-Smith"
date: "6/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts=FALSE)

library(sequential.causal)

```

```{r}
clean_sepsis_data <- function(data)
{
  data %>%
    lazy_dt(immutable = TRUE) %>% 
    mutate(
      # Simplifying ethnicity column according to NIH guidelines
      # https://grants.nih.gov/grants/guide/notice-files/not-od-15-089.html
      ethnicity_NIH = 
        case_when(grepl('AMERICAN INDIAN', ethnicity) ~ 'native',
                  grepl('ASIAN|MIDDLE EASTERN', ethnicity) ~ 'asian',
                  grepl('BLACK|CARIBBEAN', ethnicity) ~ 'black',
                  grepl('HISPANIC|SOUTH AMERICAN', ethnicity) ~ 'hispanic',
                  grepl('HAWAIIAN', ethnicity) ~ 'hawaiian',
                  grepl('WHITE|PORTUGUESE', ethnicity) ~ 'white',
                  grepl('OTHER|UNKNOWN|UNABLE|MULTI|DECLINED',
                        ethnicity) ~ 'unknown'),
      ethnicity = NULL,
      # Get 30-day mortality
      mortality_30d = ifelse(as.Date(dod) - as.Date(intime) <= 30 &
                               !is.na(dod),
                             TRUE, FALSE),
      # Dichotomize fluid intake to > or <= 8L
      # in the first 24 hours of admission
      fluids_gt8L_24h = fluids_24h_l > 8L,
      fluids_24h_l = NULL,
      # Encode diabetes as factor
      diabetes = as.factor(diabetes),
      # Encode first_service as factor
      first_service = as.factor(first_service)) %>%
    arrange(intime) %>%
    as.data.frame()
}
```

```{r}
sepsis = fread('data/sepsis_patients.csv', na.strings = "NULL") %>%
  clean_sepsis_data()

y <- as.numeric(sepsis$mortality_30d)
X <- model.matrix(~ age + gender + diabetes +
                    elixhauser_hospital + first_service,
                  data = sepsis) %>%
  as.data.frame() %>%
  mutate(`(Intercept)` = NULL)

treatment <- as.numeric(sepsis$fluids_gt8L_24h)
SL.library <- c(#"SL.earth",
  # "SL.gam",
  # "SL.glm", "SL.glmnet",
  # "SL.glm.interaction",
  # "SL.ranger")
  "SL.glmnet"
)

cs_ate <- confseq_ate(y = y,
                      X = X,
                      treatment = treatment,
                      regression_fn_1 = get_SL_fn(SL.library = SL.library,
                                                  family = gaussian()), 
                      propensity_score_fn = get_SL_fn(SL.library = SL.library,
                                                      family = binomial()),
                      t_opt = 1500,
                      times = c(3000),
                      n_cores = 1,
                      cross_fit = FALSE)
```

