---
title: "Plots for paper"
author: "Ian Waudby-Smith"
date: "08/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(gridExtra)
library(purrr)
library(dplyr)
library(sequential.causal)

plt_width = 18
plt_height = 9
theme_fn <- theme_minimal
palette <- "Set2"
```


# Start times


```{r}
# Load miscoverage_rates
load('../simulations/start_time/miscoverage_rates.RData')

n <- as.integer(names(miscoverage_rates)[[1]]) +
  length(miscoverage_rates[[1]]) - 1

load('../simulations/start_time/alpha.RData')

plt_data_lines <- as.integer(names(miscoverage_rates)) %>%
  map(function(start_time){
    df <- data.frame(t = start_time:n,
                     rate = miscoverage_rates[[as.character(start_time)]],
                     start_time = as.factor(start_time))
  }) %>%
  reduce(rbind)

shape_points <- c(100, 0:4 * 2500)
plt_data_points <- plt_data_lines[plt_data_lines$t %in% shape_points, ]

plt <- ggplot(plt_data_lines) +
  geom_line(aes(t, rate, color=start_time)) +
  geom_point(aes(t, rate, color=start_time,
                 shape=start_time), data=plt_data_points, size=2.5) +
  geom_hline(aes(yintercept = alpha),
             color='black', linetype=3, size=0.5) +
  theme_fn() + 
  labs(color="Start time", shape="Start time", linetype="Start time") +
  guides(size=FALSE) + 
  xlab('Time') + ylab('Cumulative miscoverage rate') + 
  theme(text = element_text(family="serif"),
        legend.position=c(0.85, 0.6)) +
  scale_colour_brewer(palette = palette)


ggsave(filename = 'figures/start_time_plot.pdf', plt,
       width=plt_width, height=plt_height, units='cm')
plt
```

# Confidence sequence widths

```{r}
library(pracma)
alpha <- 0.05
t_opts <- c(10, 100, 1000, 10000)
shape_points <- 10^(0:5)
t <- c(shape_points, logseq(1, 1000000, n = 10000))


plt_data_lines <- t_opts %>% map(function(t_opt){
  acs <- std_conjmix_margin(t = t,
                            rho2 = best_rho2_exact(t_opt),
                            alpha=alpha)
  naive <- naive_std_margin(t = t, alpha = alpha)
  data.frame(Time = t,
             Ratio = naive / acs,
             t_opt = as.factor(t_opt))
}) %>% reduce(rbind)

plt_data_points <- plt_data_lines[plt_data_lines$Time %in% shape_points, ]

plt <- 
  ggplot(plt_data_lines) +
  geom_line(aes(x = Time, y = Ratio, color = t_opt)) +
  geom_point(data = plt_data_points,
             aes(x = Time, y = Ratio, color = t_opt, shape = t_opt), size=2) + 
  guides(color = guide_legend(title = "t optimized"),
         shape = guide_legend(title = "t optimized")) +
  scale_x_log10(breaks = scales::trans_breaks("log10",
                                              function(x) 10^x),
                labels = scales::trans_format("log10",
                                              scales::math_format(10^.x))) +
  annotation_logticks(colour = "grey", side = "b") + 
  ylab("Ratio of confidence interval widths\nto confidence sequence widths") +
  theme_fn() + 
  theme(text = element_text(family="serif"), legend.position=c(0.75, 0.3)) +
  scale_colour_brewer(palette = palette)

ggsave("figures/CI_CS_width.pdf", width = plt_width,
       height = plt_height, units='cm')

plt
```


# Unadjusted CSs vs CIs for the ATE in randomized experiments

```{r}
load('../simulations/cs_vs_ci/cs_vs_ci.RData')

l_acs <- acs$l[start_time:n]
u_acs <- acs$u[start_time:n]

l_clt <- clt$l[start_time:n]
u_clt <- clt$u[start_time:n]

plot_df <- data.frame(t = rep(start_time:n, 4), 
                      bound = c(l_acs, u_acs, l_clt, u_clt),
                      upper_lower = c(rep('l', length(l_acs)),
                                      rep('u', length(u_acs)),
                                      rep('l', length(l_clt)),
                                      rep('u', length(u_clt))),
                      type = c(rep('CS [Thm 1]', 2*length(l_acs)),
                               rep('CI [CLT]', 2*length(l_clt))))

plt_cs <- 
  ggplot() + 
  geom_line(aes(x=t, y=bound, color=type, linetype=type), 
            data=plot_df[plot_df$upper_lower=='l',]) +
  geom_line(aes(x=t, y=bound, color=type, linetype=type), 
            data=plot_df[plot_df$upper_lower=='u',]) +
  geom_hline(yintercept=p_1 - p_2, linetype='dashed', color='gray') +
  ylab('Confidence sets for the\naverage treatment effect') + xlab('Time') +
  scale_linetype_manual(breaks=c('CI [CLT]', 'CS [Thm 1]'), values=c(3, 1)) +
  scale_x_log10(breaks = scales::trans_breaks("log10",
                                              function(x) 10^x),
                labels = scales::trans_format("log10",
                                              scales::math_format(10^.x))) +
  annotation_logticks(colour = "grey", side = "b") + 
  theme_fn() + theme(legend.position='none',
                     text = element_text(family="serif")) +
  scale_color_brewer(palette=palette)

plt_cs
# Miscoverage

plot_df <- data.frame(t = rep(start_time:n, 2),
                      miscoverage = c(acs_miscoverage,
                                      clt_miscoverage),
                      type = c(rep('CS [Thm 1]', 
                                   length(acs_miscoverage)),
                               rep('CI [CLT]',
                                   length(clt_miscoverage))))

plt_miscoverage <- ggplot(plot_df) + 
  geom_line(aes(x=t, y=miscoverage, color=type, linetype=type)) +
  geom_hline(aes(yintercept=alpha), linetype='dashed', color='gray') + 
  ylab('Cumulative miscoverage rate') + xlab('Time') +
  scale_linetype_manual(breaks=c('CI [CLT]', 'CS [Thm 1]'), values=c(3, 1)) +
  scale_x_log10(breaks = scales::trans_breaks("log10",
                                              function(x) 10^x),
                labels = scales::trans_format("log10",
                                              scales::math_format(10^.x))) +
  annotation_logticks(colour = "grey", side = "b") + 
  theme_fn() +
  theme(legend.position=c(0.75, 0.3),
        text = element_text(family="serif")) +
  scale_color_brewer(palette=palette)

plt_miscoverage

plt_both <- grid.arrange(plt_cs, plt_miscoverage, nrow=1)

ggsave('figures/miscoverage.pdf', plot = plt_both,
       width=plt_width+2, height=plt_height-2, units='cm')

  
```


# Confidence sequences for the average treatment effect

## Randomized experiments

```{r, echo=FALSE}
library(ggplot2)

load('../simulations/randomized_experiment_SL/randomized_experiment_SL.RData')

plot_df <- data.frame(t = rep(times, 6), 
                      bound = c(confseq_SL$l, confseq_SL$u,
                                confseq_glm$l, confseq_glm$u,
                                confseq_unadj$l, confseq_unadj$u),
                      upper_lower = c(rep('l', length(confseq_SL$l)),
                                      rep('u', length(confseq_SL$u)),
                                      rep('l', length(confseq_glm$l)),
                                      rep('u', length(confseq_glm$u)),
                                      rep('l', length(confseq_unadj$u)),
                                      rep('u', length(confseq_unadj$u))),
                      Model = c(rep('Super Learner', 2*length(confseq_SL$l)),
                               rep('Parametric', 2*length(confseq_glm$l)),
                               rep('Unadjusted', 2*length(confseq_unadj$l))))

plt_cs <- 
  ggplot() + 
  geom_line(aes(x=t, y=bound, color=Model, linetype=Model), 
            data=plot_df[plot_df$upper_lower=='l',]) +
  geom_line(aes(x=t, y=bound, color=Model, linetype=Model), 
            data=plot_df[plot_df$upper_lower=='u',]) +
  geom_hline(yintercept=ATE, linetype='dashed', color='gray') +
  ylab('Confidence sequences for the\naverage treatment effect') + xlab('Time') +
  scale_x_log10(breaks = scales::trans_breaks("log10",
                                              function(x) 10^x),
                labels = scales::trans_format("log10",
                                              scales::math_format(10^.x))) +
  annotation_logticks(colour = "grey", side = "b") + 
  theme_fn() + 
  theme(text = element_text(family="serif")) +
  scale_color_brewer(palette=palette)

ggsave('figures/CS_randomized.pdf',
       width=plt_width, height=plt_height, units='cm')
plt_cs

```

## Observational studies

```{r, echo=FALSE}
library(ggplot2)

load('../simulations/observational_study_SL/observational_study_SL.RData')

plot_df <- data.frame(t = rep(times, 6), 
                      bound = c(confseq_SL$l, confseq_SL$u,
                                confseq_glm$l, confseq_glm$u,
                                confseq_unadj$l, confseq_unadj$u),
                      upper_lower = c(rep('l', length(confseq_SL$l)),
                                      rep('u', length(confseq_SL$u)),
                                      rep('l', length(confseq_glm$l)),
                                      rep('u', length(confseq_glm$u)),
                                      rep('l', length(confseq_unadj$u)),
                                      rep('u', length(confseq_unadj$u))),
                      Model = c(rep('Super Learner', 2*length(confseq_SL$l)),
                               rep('Parametric', 2*length(confseq_glm$l)),
                               rep('Unadjusted', 2*length(confseq_unadj$l))))

plt_cs <- 
  ggplot() + 
  geom_line(aes(x=t, y=bound, color=Model, linetype=Model), 
            data=plot_df[plot_df$upper_lower=='l',]) +
  geom_line(aes(x=t, y=bound, color=Model, linetype=Model), 
            data=plot_df[plot_df$upper_lower=='u',]) +
  geom_hline(yintercept=ATE, linetype='dashed', color='gray') +
  ylab('Confidence sequences for the\naverage treatment effect') + xlab('Time') +
  scale_x_log10(breaks = scales::trans_breaks("log10",
                                              function(x) 10^x),
                labels = scales::trans_format("log10",
                                              scales::math_format(10^.x))) +
  annotation_logticks(colour = "grey", side = "b") + 
  theme_fn() + 
  theme(text = element_text(family="serif")) +
  scale_color_brewer(palette=palette)

ggsave('figures/CS_observational.pdf',
       width=plt_width, height=plt_height, units='cm')
plt_cs

```

